- hosts: all
  pre_tasks:
      - name: Update and upgrade apt packages
        become: true
        apt:
            upgrade: yes
            update_cache: yes
            cache_valid_time: 86400
  vars_files:
    - group_vars/webservers.yml

  roles:
    - { role: datadog.datadog, become: yes}
    - geerlingguy.pip

  tasks:
    - name: install docker package
      pip:
        name: docker

    - name: deploy redmine app
      docker_container:
        name: redmine
        image: redmine
        auto_remove: yes
        pull: yes
        ports:
          - 80:3000
        state: started
        env:
          REDMINE_DB_DATABASE: '{{ REDMINE_DB_DATABASE }}'
          REDMINE_DB_POSTGRES: '{{ REDMINE_DB_POSTGRES }}'
          REDMINE_DB_PORT: '{{ REDMINE_DB_PORT }}'
          REDMINE_DB_USERNAME: '{{ REDMINE_DB_USERNAME }}'
          REDMINE_DB_PASSWORD: '{{ REDMINE_DB_PASSWORD }}'

    - name: install datadog
      include_role:
        name: datadog.datadog
