- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - geerlingguy.pip
    - datadog.datadog

  vars:
    pip_install_packages:
      - name: docker

  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

  tasks:
    - name: deploy redmine app
      docker_container:
        name: redmine
        image: redmine
        ports:
          - 80:3000
        state: started
        env:
          REDMINE_DB_DATABASE: "{{ redmine_db_database }}"
          REDMINE_DB_POSTGRES: "{{ redmine_db_postgres }}"
          REDMINE_DB_PORT: "{{ redmine_db_port }}"
          REDMINE_DB_USERNAME: "{{ redmine_db_username }}"
          REDMINE_DB_PASSWORD: "{{ redmine_db_password }}"

