- hosts: all

  roles:
    - { role: datadog.datadog, become: yes}
    - geerlingguy.pip

  tasks:
    - name: install docker package
      pip:
        name: docker

    - name: deploy redmine app
      community.docker.docker_container:
        name: redmine
        image: redmine:latest
        recreate: yes
        ports:
          - 80:3000
        state: started
        env:
          REDMINE_DB_DATABASE: "{{ redmine_pg_db }}"
          REDMINE_DB_POSTGRES: "{{ redmine_pg_host }}"
          REDMINE_DB_PORT: "{{ redmine_pg_port }}"
          REDMINE_DB_USERNAME: "{{ redmine_pg_username }}"
          REDMINE_DB_PASSWORD: "{{ redmine_pg_password }}"

    - name: install datadog
      include_role:
        name: datadog.datadog
