- hosts: all

  roles:
    - { role: datadog.datadog, become: yes}
    - geerlingguy.pip

  vars_files:
    - group_vars/webservers.yml

  tasks:
    - name: install datadog
      include_role:
        name: datadog.datadog

    - name: install docker package
      pip:
        name: docker

    - name: deploy redmine app
      docker_container:
        name: redmine
        image: redmine
        auto_remove: yes
        pull: yes
        ports:
          - 80:3000
        state: started
        env:
          REDMINE_DB_DATABASE: "{{ REDMINE_DB_DATABASE }}"
          REDMINE_DB_POSTGRES: "{{ REDMINE_DB_POSTGRES }}"
          REDMINE_DB_PORT: "{{ REDMINE_DB_PORT }}"
          REDMINE_DB_USERNAME: "{{ REDMINE_DB_USERNAME }}"
          REDMINE_DB_PASSWORD: "{{ REDMINE_DB_PASSWORD }}"

